spring.application.name=InternTrack Pro

# Easy local demo database. It saves data inside the project folder.
spring.datasource.url=jdbc:h2:file:./data/interntrackdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


server.port=${PORT:8080}
# To use MySQL later, comment the H2 datasource above and uncomment below:
# spring.datasource.url=jdbc:mysql://localhost:3306/interntrack_db
# spring.datasource.username=root
# spring.datasource.password=your_mysql_password
# spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
